stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
    outs:
      - artifacts/raw
  data_preprocessing:
    cmd: python src/components/data_preprocessing.py
    deps:
      - artifacts/raw
      - src/components/data_preprocessing.py
    outs:
      - artifacts/processed
